version: "3.8"

services:
  xdcc_downloader_web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: xdcc-downloader-web
    container_name: xdcc_downloader_web
    ports:
      - "9999:8888"
    volumes:
      - /volume1/Downloads:/downloads
    environment:
      USER_ID: 1026
      GROUP_ID: 100
      TZ: 'Europe/Rome'
    
